# Generated by Django 2.0.6 on 2019-04-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placarPPR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_ano',
            field=models.CharField(max_length=200),
        ),
    ]
