# Generated by Django 2.0.6 on 2019-04-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placarPPR', '0002_auto_20190427_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='atingido_ano',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_acum',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_ano',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='percent_ating',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='post',
            name='qt_salarios',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='real_acum',
            field=models.CharField(max_length=20),
        ),
    ]
