# Generated by Django 2.0.6 on 2019-04-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placarPPR', '0004_auto_20190427_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='atingido_ano',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='percent_ating',
            field=models.CharField(max_length=10),
        ),
    ]
