# Generated by Django 2.0.6 on 2019-04-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placarPPR', '0005_auto_20190427_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='farol',
            field=models.CharField(max_length=10),
        ),
    ]
