# Generated by Django 2.0.6 on 2019-04-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placarPPR', '0006_auto_20190427_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
